version: '3.8'

services:
  node1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node1
    networks:
      mpi_net:
        ipv4_address: 172.20.0.2
    tty: true
    stdin_open: true
    volumes:
      - .:/workspace

  node2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node2
    networks:
      mpi_net:
        ipv4_address: 172.20.0.3
    tty: true
    stdin_open: true
    volumes:
      - .:/workspace

  node3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node3
    networks:
      mpi_net:
        ipv4_address: 172.20.0.4
    tty: true
    stdin_open: true
    volumes:
      - .:/workspace

networks:
  mpi_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
